# Generated by Django 5.1.4 on 2024-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0021_remove_administrator_hospital_hospital_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrative',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='administrator',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='laborantin',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='radiologist',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
    ]
