# Generated by Django 5.1.4 on 2024-12-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0022_administrative_gender_administrator_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
    ]
