# Generated by Django 5.1.4 on 2025-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0024_remove_care_dpi_remove_dpi_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pastMedical',
            field=models.TextField(null=True),
        ),
    ]
