# Generated by Django 5.1.4 on 2025-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0025_patient_pastmedical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pastMedical',
            field=models.TextField(default='', null=True),
        ),
    ]
