# Generated by Django 5.1.3 on 2024-12-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpi', '0024_remove_care_dpi_remove_dpi_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lastedFor', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(max_length=100)),
                ('resume', models.CharField(blank=True, max_length=300)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=500)),
                ('care', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(blank=True)),
                ('nurse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='dpiOps.medicalcondition')),
            ],
        ),
        migrations.CreateModel(
            name='Bloodwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('conductionDate', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('results', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodworks', to='dpiOps.medicalcondition')),
            ],
            options={
                'ordering': ['-issueDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('validationDate', models.DateField(blank=True)),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dpiOps.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('conductionDate', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='examinations/')),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='dpiOps.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
            options={
                'ordering': ['-issueDate'],
                'abstract': False,
            },
        ),
    ]
