# Generated by Django 5.1.4 on 2024-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
