# Generated by Django 5.1.3 on 2024-12-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0024_remove_care_dpi_remove_dpi_patient_and_more'),
        ('dpiOps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloodwork',
            new_name='Baio_test',
        ),
        migrations.RenameField(
            model_name='baio_test',
            old_name='results',
            new_name='resume',
        ),
        migrations.CreateModel(
            name='Radio_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('conductionDate', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('resume', models.TextField()),
                ('results', models.JSONField()),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='dpiOps.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
            options={
                'ordering': ['-issueDate'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
