# Generated by Django 5.1.4 on 2024-12-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0020_remove_care_dpi_remove_dpi_patient_remove_test_dpi_and_more'),
        ('dpiOps', '0002_alter_care_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='validationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PrescriptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dpiOps.prescription')),
            ],
        ),
    ]
