# Generated by Django 5.1.3 on 2024-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0002_rename_bloodwork_baio_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baio_test',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='baio_test',
            name='priorite',
            field=models.CharField(choices=[('normal', 'Normal'), ('dangerous', 'Dangerous')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baio_test',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radio_test',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='radio_test',
            name='priorite',
            field=models.CharField(choices=[('normal', 'Normal'), ('dangerous', 'Dangerous')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='radio_test',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baio_test',
            name='conductionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baio_test',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radio_test',
            name='conductionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radio_test',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radio_test',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
