# Generated by Django 5.1.4 on 2024-12-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0020_remove_care_dpi_remove_dpi_patient_remove_test_dpi_and_more'),
        ('dpiOps', '0003_prescription_doctor_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='dpi.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dpi.patient'),
        ),
    ]
