# Generated by Django 5.1.3 on 2024-12-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0003_baio_test_description_baio_test_priorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baio_test',
            name='mesurements',
            field=models.JSONField(default=dict),
        ),
    ]
