# Generated by Django 5.1.4 on 2024-12-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0024_remove_care_dpi_remove_dpi_patient_and_more'),
        ('dpiOps', '0004_baio_test_mesurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('conductionDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('resume', models.TextField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('priorite', models.CharField(choices=[('normal', 'Normal'), ('dangerous', 'Dangerous')], max_length=10, null=True)),
                ('results', models.JSONField(default=str)),
                ('medicalCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseTests', to='dpiOps.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
            options={
                'ordering': ['-issueDate'],
                'abstract': False,
            },
        ),
    ]
