# Generated by Django 5.1.4 on 2024-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0004_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Failed', 'failed')], default='Pending', max_length=50),
        ),
    ]
