# Generated by Django 5.1.4 on 2024-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0005_alter_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
