# Generated by Django 5.1.4 on 2025-01-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpiOps', '0007_alter_radio_test_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dpiOps.prescription')),
            ],
        ),
    ]
